### ISSUE TITLE
Tried installing and says Subprocess-exited-with-error

### ISSUE THREAD

**Issue by Swassyman** [coreylammie/MemTorch#166]
```
 error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "C:\Users\swara\AppData\Roaming\Python\Python312\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\swara\AppData\Roaming\Python\Python312\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\swara\AppData\Roaming\Python\Python312\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\swara\AppData\Local\Temp\pip-build-env-iva3592h\overlay\Lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\swara\AppData\Local\Temp\pip-build-env-iva3592h\overlay\Lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "C:\Users\swara\AppData\Local\Temp\pip-build-env-iva3592h\overlay\Lib\site-packages\setuptools\build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\swara\AppData\Local\Temp\pip-build-env-iva3592h\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 4, in <module>
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by AverageY** [comment]
I faced a similar issue trying to install memtorch in the virtual environment.
1) First clone the repo and go down the path of installing memtorch via their `setup.py`
2) upgrade the setup tools : `python -m pip install --upgrade pip setuptools wheel`
3) install the required dependencies(according to the setup file) : 
`pip install numpy pandas scipy scikit-learn torch>=1.2.0 torchvision matplotlib seaborn ipython lmfit`
4) While doing this, I came across a secondary issue
on line 95 in `setup.py`
```
install_requires=[
            "numpy",
            "pandas",
            "scipy",
            "sklearn", # Line 99, have to change this to scikit-learn
            "torch>=1.2.0",
            "torchvision",
            "matplotlib",
            "seaborn",
            "ipython",
            "lmfit",
        ]
```

make the changes at line 99

```
install_requires=[
            "numpy",
            "pandas",
            "scipy",
            "scikit-learn",
            "torch>=1.2.0",
            "torchvision",
            "matplotlib",
            "seaborn",
            "ipython",
            "lmfit",
        ]
```

5) save the setup.py and make sure above dependencies are installed and setuptools are upgraded as in step 3 and step 2.
then do: `pip install .`
