### ISSUE TITLE
ModuleNotFoundError: No module named 'memtorch_bindings'

### ISSUE THREAD

**Issue by AngelinaRanhh** [coreylammie/MemTorch#78]
After I installed memtorch, I can find it in conda list, But when I import it,  I met the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rhh/myfiles/MemTorch/memtorch/__init__.py", line 4, in <module>
    from memtorch.bh import *
  File "/home/rhh/myfiles/MemTorch/memtorch/bh/__init__.py", line 1, in <module>
    from .crossbar import *
  File "/home/rhh/myfiles/MemTorch/memtorch/bh/crossbar/__init__.py", line 1, in <module>
    from .Crossbar import *
  File "/home/rhh/myfiles/MemTorch/memtorch/bh/crossbar/Crossbar.py", line 14, in <module>
    from .Tile import gen_tiles
  File "/home/rhh/myfiles/MemTorch/memtorch/bh/crossbar/Tile.py", line 11, in <module>
    import memtorch_bindings
ModuleNotFoundError: No module named 'memtorch_bindings'

Is anyone can help me? Thanks.

**Comment by coreylammie** [comment]
Hi @AngelinaRanhh,

Thank you for reaching out! 

I have just checked the current build, and unfortunately, I cannot reproduce the aforementioned error. To ensure the most up-to-date version is being used, may you please try running the following commands:

```
git clone --recursive https://github.com/coreylammie/MemTorch
cd MemTorch
sed -i 's/CUDA = False/CUDA = True/g' setup.py # Only execute this command if you are installing MemTorch with CUDA support. If you are using Windows, instead of running this command, simply change CUDA = False to CUDA = True in setup.py
pip install --upgrade --no-deps --force-reinstall . --log log.txt
```

If this does not fix your problem, to help me identify the issue, could you please upload `log.txt` to your reply and specify what version of memtorch you have installed and what operating system you are using? 

Kind Regards,

Corey.

**Comment by AngelinaRanhh** [comment]
The followings are my commands:
(base) rhh@user-Super-Server:~/myfiles/MemTorch$ sed -i 's/CUDA = False/CUDA = True/g' setup.py
(base) rhh@user-Super-Server:~/myfiles/MemTorch$ pip install --upgrade --no-deps --force-reinstall . --log log.txt

These are my log info:
Processing /home/rhh/myfiles/MemTorch
Building wheels for collected packages: memtorch
  Building wheel for memtorch (setup.py) ... error
  ERROR: Failed building wheel for memtorch
  Running setup.py clean for memtorch
Failed to build memtorch
Installing collected packages: memtorch
  Attempting uninstall: memtorch
    Found existing installation: memtorch 1.1.0
    Uninstalling memtorch-1.1.0:
      Successfully uninstalled memtorch-1.1.0
    Running setup.py install for memtorch ... error
  Rolling back uninstall of memtorch
  Moving to /home/rhh/anaconda3/lib/python3.8/site-packages/cuda_quantization.cpython-38-x86_64-linux-gnu.so
   from /tmp/pip-uninstall-r69jalrm/cuda_quantization.cpython-38-x86_64-linux-gnu.so
  Moving to /home/rhh/anaconda3/lib/python3.8/site-packages/memtorch-1.1.0.dist-info/
   from /home/rhh/anaconda3/lib/python3.8/site-packages/~emtorch-1.1.0.dist-info
  Moving to /home/rhh/anaconda3/lib/python3.8/site-packages/memtorch/
   from /home/rhh/anaconda3/lib/python3.8/site-packages/~emtorch
  Moving to /home/rhh/anaconda3/lib/python3.8/site-packages/quantization.cpython-38-x86_64-linux-gnu.so
   from /tmp/pip-uninstall-r69jalrm/quantization.cpython-38-x86_64-linux-gnu.so
  Moving to /home/rhh/anaconda3/lib/python3.8/site-packages/tests/
   from /home/rhh/anaconda3/lib/python3.8/site-packages/~ests
ERROR: Command errored out with exit status 1: /home/rhh/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-wwtwuf97/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-wwtwuf97/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-5nfla04v/install-record.txt --single-version-externally-managed --compile --install-headers /home/rhh/anaconda3/include/python3.8/memtorch Check the logs for full command output.

**Comment by coreylammie** [comment]
Hi @AngelinaRanhh,

This looks like a version-conflict issue to me. The most recent version of MemTorch on PyPi is 1.1.2, the same version of the current build on the master branch. 

Your log indicates that version 1.1.0 is throwing an error. To ensure the most up-to-date version of MemTorch is being installed, could you please try to uninstall the currently installed version, and manually install the most recent version? This can be done as follows:

```
pip uninstall memtorch
git clone --recursive https://github.com/coreylammie/MemTorch
cd MemTorch
sed -i 's/CUDA = False/CUDA = True/g' setup.py
pip install . --log log.txt
```

Alternatively, the latest release on PyPi can be installed:

```
pip uninstall memtorch
pip install memtorch=1.1.2 --log log.txt
```

Please note that in order to build MemTorch from its source distribution with CUDA support, the CUDA Toolkit and Microsoft Visual C++ Build Tools are required.

**Comment by AngelinaRanhh** [comment]
I have installed the Visual Code with the C++ Build Tools, and tried the two methods above. The errors are same as before.
as the info are still same as following :

Building wheel for memtorch (setup.py) ... error
  ERROR: Failed building wheel for memtorch
  Running setup.py clean for memtorch
Failed to build memtorch
Installing collected packages: memtorch
    Running setup.py install for memtorch ... error
ERROR: Command errored out with exit status 1: /home/rhh/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-aiwyk5fk/memtorch/setup.py'"'"'; __file__='"'"'/tmp/pip-install-aiwyk5fk/memtorch/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-g7kldcuu/install-record.txt --single-version-externally-managed --compile --install-headers /home/rhh/anaconda3/include/python3.8/memtorch Check the logs for full command output.

I am sure the  CUDA Toolkit is ok on my system, and could you tell me how to check the Microsoft Visual C++ Build Tools in linux.

Thanks very much.

**Comment by coreylammie** [comment]
Hi @AngelinaRanhh,

Thank you for following these steps. Ideally, the `ninja` build tool should be used in conjunction with `Microsoft Visual C++ Build Tools`, however, technically speaking files should be able to be compiled using any C++ compiler with C++11 support, as long as associated tools are on accessible on `PATH`. You can check if a C++ compiler and ninja are available using the commands `cl` or `g++` (assuming you are using either `clang` or `gcc`/`g++`), and `ninja`, respectively. 

After checking the above, could you please upload the log file generated by pip (`log.txt`) so that I can diagnose your specific compiler error? This can be done by dragging and dropping the file to the comment text-box.

**Comment by 24367452** [comment]
I also encountered this problem. Do you remember how to solve it
